version: "3.9"

services:
  machine:
    image: cartesi/dapp:${DAPP_NAME:?undefined DAPP_NAME}-devel-machine
    command: xxd -c 256 -p latest/hash; sleep 3
    volumes:
      - machine:/var/opt/cartesi/machine-snapshots

  authority-deployer:
    image: gbbabarros/rollups-hardhat:1.0.1
    command:
      [
        "deploy",
        "--network",
        "${NETWORK:?undefined NETWORK}",
        "--export",
        "/home/node/rollups.json",
      ]
    volumes:
      - ./deployments/${NETWORK:?undefined NETWORK}:/home/node
    environment:
      - MNEMONIC=${MNEMONIC:?undefined MNEMONIC}
      - RPC_URL=${RPC_URL:?undefined RPC_URL}
      - NETWORK=${NETWORK:?undefined NETWORK}

  dapp-deployer:
    build: ./build/testnet-dapp-deployer
    depends_on:
      machine:
        condition: service_started
      authority-deployer:
        condition: service_completed_successfully
    volumes:
      - machine:/var/opt/cartesi/machine-snapshots:ro
      - ./deployments:/deployments
      - ./build:/build
    environment:
      - MNEMONIC=${MNEMONIC:?undefined MNEMONIC}
      - NETWORK=${NETWORK:?undefined NETWORK}
      - RPC_URL=${RPC_URL:?undefined RPC_URL}
      - DAPP_NAME=${DAPP_NAME:?undefined DAPP_NAME}

volumes:
  machine: {}
